name: "Birth Github Setup"
description: "Action to setup Birth projects on Github"
author: "Birth Software"

runs:
  using: "composite"
  steps:
    - name: Birth Github Setup
      shell: bash
      run: |
        set -eux
        BIRTH_NATIVE_OS_STRING=$OSTYPE

        case "$BIRTH_NATIVE_OS_STRING" in
            darwin*) BIRTH_OS="macos";;
            linux*) BIRTH_OS="linux";;
            msys*) BIRTH_OS="windows";;
            *) exit 1;;
        esac

        if [[ -n "${BIRTH_LINKAGE_MODE+x}" ]]; then
            echo "BIRTH_LINKAGE_MODE=$BIRTH_LINKAGE_MODE" >> $GITHUB_ENV
            case "$BIRTH_LINKAGE_MODE" in
                static) echo "LLVM_LINK_LLVM_DYLIB=OFF" >> $GITHUB_ENV;;
                dynamic) echo "LLVM_LINK_LLVM_DYLIB=ON" >> $GITHUB_ENV;;
                *) exit 1;;
            esac
        fi
        
        BIRTH_NATIVE_ARCH_STRING="$(uname -m)"
        
        case "$BIRTH_NATIVE_ARCH_STRING" in
            x86_64) BIRTH_ARCH="x86_64";;
            arm64) BIRTH_ARCH="aarch64";;
            aarch64) BIRTH_ARCH="aarch64";;
            *) exit 1;;
        esac
        
        echo "BIRTH_NATIVE_OS_STRING=$BIRTH_NATIVE_OS_STRING" >> $GITHUB_ENV
        echo "BIRTH_NATIVE_ARCH_STRING=$BIRTH_NATIVE_ARCH_STRING" >> $GITHUB_ENV
        echo "BIRTH_OS=$BIRTH_OS" >> $GITHUB_ENV
        echo "BIRTH_ARCH=$BIRTH_ARCH" >> $GITHUB_ENV

        MATRIX_OS=${{ inputs.os }}
        case $BIRTH_OS in
          linux)
            uname -a
            lsb_release -a
            lscpu
            df -h
            sudo apt-get update && sudo apt-get install -y ninja-build clang mold llvm
            ;;
          macos)
            uname -a
            sw_vers -productVersion
            df -h
            brew install ninja coreutils llvm
            ;;
          windows)
            systeminfo

            choco install ninja gnuwin32-coreutils.install
            ;;
        esac
