name: "Birth Github Setup"
description: "Action to setup Birth projects on Github"
author: "Birth Software"

runs:
  using: "composite"
  steps:
    - name: Birth Github Setup
      shell: bash
      run: |
        set -eux
        clang -print-effective-triple
        clang -print-target-triple
        clang -std=gnu2x -g -o $GITHUB_ACTION_PATH/main $GITHUB_ACTION_PATH/main.c
        $GITHUB_ACTION_PATH/main $GITHUB_ACTION_PATH/helper.sh
        source $GITHUB_ACTION_PATH/helper.sh

        echo "BIRTH_OS=$BIRTH_OS" >> $GITHUB_ENV
        echo "BIRTH_ARCH=$BIRTH_ARCH" >> $GITHUB_ENV

        MATRIX_OS=${{ inputs.os }}
        case $BIRTH_OS in
          linux)
            uname -a
            sudo apt-get update && sudo apt-get install -y ninja-build mold
            lsb_release -a
            lscpu
            df -h
            ;;
          macos)
            uname -a
            sw_vers -productVersion
            df -h
            brew install ninja coreutils llvm
            ;;
          windows)
            systeminfo
            choco install ninja gnuwin32-coreutils.install
            ;;
        esac
