name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate-config:
    runs-on: ubuntu-latest
    outputs:
      BIRTH_GITHUB_TARGETS: ${{ steps.generate-config.outputs.BIRTH_GITHUB_TARGETS }}
      BIRTH_ORACLE_LINUX_IMAGE: ${{ steps.generate-config.outputs.BIRTH_ORACLE_LINUX_IMAGE }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Generate config
        id: GENERATE-CONFIG
        uses: birth-software/github-config@v3
  test:
    needs: generate-config
    strategy:
      matrix:
        os: ${{ fromJSON(needs.generate-config.outputs.BIRTH_GITHUB_TARGETS) }}
    runs-on: ${{ matrix.os }}
    env:
      BIRTH_ORACLE_LINUX_IMAGE: ${{ needs.generate-config.outputs.BIRTH_ORACLE_LINUX_IMAGE }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Own action
        uses: ./
      - name: Check
        shell: bash
        run: |
          set -eux
          echo $BIRTH_NATIVE_OS_STRING
          echo $BIRTH_NATIVE_ARCH_STRING
          echo $BIRTH_ARCH
          echo $BIRTH_OS

